### ISSUE TITLE
Sugoi Translator usage

### ISSUE THREAD

**Issue by leminhyen2** [xulihang/ImageTrans_plugins#1]
Hey, do you host sugoi translator on the server or does user download Sugoi locally and use it with ImageTrans?

**Comment by xulihang** [comment]
Just locally. Would be great if you could provide an API service.

**Comment by leminhyen2** [comment]
I don't know if I would. I was surprised to find out a program make a translation plugin from Sugoi. Would be nice if you informed me beforehand

**Comment by xulihang** [comment]
The plugin is done as requested by your users. If you want to restrict the usage, you'd better write a statement.

**Comment by leminhyen2** [comment]
For now, no problem from my side as long as users download Sugoi locally.
