### ISSUE TITLE
No DeepL plugin on the release file

### ISSUE THREAD

**Issue by anys357** [xulihang/ImageTrans_plugins#2]
Hi,
Can you please update the release file?
Most of the plugins didn't receive an update, some even are missing like the DeepLfreeMT
Thanks for your hard work ^^

**Comment by xulihang** [comment]
The plugins are stable. They don't need an update. The DeepL free plugin is included in v1.6.3.

In case you need to install it manually, here are the plugin files of DeepL free.

[deeplfree_plugin.zip](https://github.com/xulihang/ImageTrans_plugins/files/8459046/deeplfree_plugin.zip)

**Comment by anys357** [comment]
Thanks for your quick answer :)
