### ISSUE TITLE
Manga OCR instructions?

### ISSUE THREAD

**Issue by randoomdude** [xulihang/ImageTrans_plugins#3]
I don't really understand the instructions for the manga ocr, I use windows but I downloaded python but didn't really understand how to use the commands, so I just used the instructions for the windows users but now that the server is running how does that make ImageTrans use the better manga OCR? I'm having trouble reading some manga images so I thought it might be useful, but I don't know how to make it work
![image](https://user-images.githubusercontent.com/6027132/208036087-8d5289e3-f79a-4d49-a1e3-2de812a9d794.png)

**Comment by xulihang** [comment]
Check this: https://github.com/xulihang/ImageTrans_plugins/tree/master/mangaOCR

You need to install the plugin.

**Comment by StephenDSmith** [comment]
Hi, I'm also having trouble and I'm struggling to follow the guide in the link above. I have the server running in a folder, does the `manga-ocr` folder have to be inside the ImageTrans folder?

Also I don't get what you mean by install the plugin, what plugin?
I followed these steps:
`For convenience, you can also use the Windows package:

1. Download and unzip [manga-ocr](https://github.com/xulihang/ImageTrans_plugins/releases/download/plugins/manga-ocr.zip).
2. (Optional) Download the [model](https://github.com/xulihang/ImageTrans_plugins/releases/download/plugins/manga-ocr-model.zip) and unzip it to manga-ocr's folder in the previous step.
3.  Run run.bat and wait for the server to get ready.`

**Comment by xulihang** [comment]
manga-ocr does not need to stay in the same folder.

Do step four to install the plugins:

> Unzip the [plugin files](https://github.com/xulihang/ImageTrans-docs/files/7919869/manga-ocr-plugin.zip) in ImageTrans's plugins folder and restart ImageTrans.
