### ISSUE TITLE
[Suggestion] Allow custom IP/FQDN and Port for SugoiMT plugin

### ISSUE THREAD

**Issue by fennelfora** [xulihang/ImageTrans_plugins#4]
The Sugoi Translation plugin works great!

Is there any chance that we could have a way to customize the IP address or fully qualified domain name and the port? I don't know how common this is, but I actually run Sugoi on one PC on my local network. I use it for Translator++, Screen Translator, Visual Novel translation, some other things and now ImageTrans. Unfortunately, with ImageTrans I need to use ImageTrans directly on that one PC for it to work. I can't run it from my MacBook Pro because I'm unable to change the IP and port.

Is there any chance we could have a way to do that? It doesn't need to be GUI based. It could be something easy like a text file that we have to edit.

Anyway, thanks for ImageTrans, it's awesome!

**Comment by fennelfora** [comment]
Oh one more thing. I want to clarify where the plugins folder is for macOS users. Maybe this can be added to the documentation. It is under:

ImageTrans > Contents > Java > plugins

It's a bit confusing because there are other Plugins folders within the ImageTrans application on Mac so it's easy to put a plugin in the wrong place.

**Comment by xulihang** [comment]
I've updated the plugin. You can set the URL in the preferences.

[sugoiMT.zip](https://github.com/xulihang/ImageTrans_plugins/files/10498099/sugoiMT.zip)

https://github.com/xulihang/ImageTrans_plugins/commit/ee2fe54111335f05b0e800080fb3822b73145748

**Comment by fennelfora** [comment]
Wow, you're fast! Thank you. I tried to use it, but I think there is something wrong. If I change the port on my server to how I used to have it, (14341) and update "url" under File > Preferences > API > sugoi with proper IP and port, the translate buttons and features no longer work.

I tested using Postman (www.postman.com) and I can confirm that my server works fine. I can send a post request from another computer to the server and get back a translation. So that means it's not the local Windows Firewall blocking or something wrong with the server.

If I change the sugoi server back to port 14366 the translate buttons work again if I run ImageTrans directly on the server.

Is there a log I can look at or provide to help troubleshoot what the issue is?

**Comment by xulihang** [comment]
I see. I forgot how the plugin reads the preferences.

Please use the new version:

[sugoiMT.zip](https://github.com/xulihang/ImageTrans_plugins/files/10506547/sugoiMT.zip)

https://github.com/xulihang/ImageTrans_plugins/commit/3eb722a4c554dbaacdb06d9f0080f01c4e872c38

**Comment by fennelfora** [comment]
Yes, that works great! Thank you very much!
